name: tatlacas_flutter_core
description: Bootstrap for tatlacas flutter apps
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.2
  http: ^0.13.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  tatlacas_sql_storage:
    path: ../tatlacas_sql_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
