name: tatlacas_flora_core
description: Bootstrap for tatlacas flutter apps
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  auto_animated: ^3.0.1
  bloc: ^8.0.2
  bloc_concurrency: ^0.2.2
  dio: ^5.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_lints: ^4.0.0
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
