name: tatlacas_flutter_core
description: Bootstrap for tatlacas flutter apps
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  http: ^0.13.4
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  auto_animated: ^3.0.1
  flutter_lints: ^2.0.1
  universal_platform: ^1.0.0+1
  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
