name: tatlacas_flutter_core
description: Bootstrap for tatlacas flutter apps
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_animated: ^3.0.1
  bloc: ^8.0.2
  dio: ^5.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_lints: ^2.0.1
  http: ^1.1.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
